export interface MatchData {
    id: string,
    player1_id      : string  ,
    player2_id      : string  ,
    status          : string  ,
    contest_id      : string  ,
    problem_index   : string  ,
    duration?       : number  ,
    winner_user_id  : string  ,
    created_at?     : string  ,
    finished_at?    : string  ,
    updated_at?     : string  ,
    player1_ready   : boolean ,
    player2_ready   : boolean ,
}